version: "3.8"

services:
    backend:
        container_name: cartoleiro-node-backend
        build:
            context: "./node-api"
            dockerfile: Dockerfile
        volumes: 
            - "./node-api:/app"
        ports: 
            - "3333:3333"

    frontend:
        container_name: cartoleiro-frontend  
        build:
            context: "./frontend"
            dockerfile: Dockerfile
        volumes:
            - "./frontend:/app"
            - "/app/node_modules"
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true

    
